### ISSUE TITLE
Update workflow runs in general to specific order

### ISSUE THREAD

**Issue by Chralt98** [zeitgeistpm/zeitgeist#665]
I just waited for the fuzz tests a long time, just to get [a workflow error](https://github.com/zeitgeistpm/zeitgeist/runs/6788662220?check_suite_focus=true) in not the fuzz tests, but in clippy.

Clippy should definitely come before the fuzz tests. 

Maybe this order: Misc -> Clippy -> Standalone -> Parachain -> Fuzz

Clippy compiles the full node too. That's why it takes so long. We could save time when compiling the zeitgeist node once. Is there a way to avoid compiling the same in clippy, standalone etc.. ? If yes, this would lead to getting much earlier results of the workflows and therefore speed up development time.

**Comment by Chralt98** [comment]
I investigated time to understand the GitHub Workflow Settings. I found, that [this](https://github.com/zeitgeistpm/zeitgeist/blob/7e1cf3d7fdece62ce054fc8603977ba0b9e54395/.github/workflows/rust.yml#L35-L36) caches the rust crates if they were already compiled. I think about ordering the matrix in a way, that the order works as mentioned above like the following [here](https://github.com/zeitgeistpm/zeitgeist/blob/7e1cf3d7fdece62ce054fc8603977ba0b9e54395/.github/workflows/rust.yml#L38-L39).

```yml
      - name: Formatting
        run: ./scripts/tests/format.sh
      - name: Unit Tests
        run: ./scripts/tests/misc.sh
      - name: Standalone Checks
        run: ./scripts/tests/standalone.sh
      - name: Parachain Checks
        run: ./scripts/tests/parachain.sh
```
